### ISSUE TITLE
build status isnt updated when i am working on another screen

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#14] opened 2023-01-27 14:01 UTC
**Is your feature request related to a problem? Please describe.**
today i was waiting for around 20 minutes for my build to deploy. so i was working in another window waiting for the build to finish. But after 20 minutes i was wondering why it took so long. as it turns out forest doesn't refresh the build status if the user has a different window open

**Describe the solution you'd like**
forest should refresh the build status if you are working in another window

**Describe alternatives you've considered**
keep my computer on forest and my phone on reddit

**Additional context**

**Comment by Forest-Gio** [comment] 2023-01-30 08:42
Hey @cvanh,

Thank you for your request.

I have build it so the timer pauses when the window loses focus to prevent the APP from sending requests to the API.

It's good to check your build when it's running ;) 

I'll talk to Massim to see if we want to change this, but i think that'll be a negative, but u never know.

Keeping this open until i've received confirmation from Massim

**Comment by mass-im** [comment] 2023-02-09 10:54
Hey nice one! But this is really expected/intended behavior.
If we would want to change this I think we should think about notifications. Maybe using the browser, email or something we did not think about yet. This is already on our list albeit not at the top yet.
Closing this for now.

**Closed by mass-im** 2023-02-09 10:54 UTC
Labels: enhancement, question
