### ISSUE TITLE
[BUG] cannot create enironment in existing project

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#32] opened 2023-03-24 11:46 UTC
**Describe the bug**
see title

**Include relevant information**
When reporting in issue about environments, builds, databases or volumes include the IDs that are relevant. IDs might be part of the URL or can be found in the response for the relevant page or request.
(don't share project and environment names if you can. See `check for sensitive information` at the end of the template)

**To Reproduce**
1. go to a existing project
2. create a new environment in this project
3. configure the blueprint like on the screenshot
5. you see the create button is gray because it wants the team name

**Expected behavior**
it's let me create a project

**Screenshots**
<img width="747" alt="Capture d’écran 2023-03-24 à 12 43 50" src="https://user-images.githubusercontent.com/39672378/227512597-d035f439-8c0a-4ccc-84ce-39ba51d23e45.png">

**Comment by Forest-Gio** [comment] 2023-03-24 11:50
Hey!

Thank you for your bug report.

I have 2 things to add;

1. Your bug report is false. It isn't expecting a team name; the issue is that it's validating the input fields and your blueprint builder, but for some reason when you're done filling in your blueprint it doesn't update the validity.
2. There are 2 work arounds; You can either fill in your branch name after filling in the blueprint; or just type something in your branch name and delete that so the validity state gets updated.

We are aware of the issue and working on a fix!

Thank you.

**Comment by Forest-Gio** [comment] 2023-03-28 10:51
Hey @cvanh ,

I've deployed a fix for this issue.

Thank you for taking the time to file a bug report and bringing this to our attention.

I hope you have a nice day!

Ciao for now,

Giovanni

**Closed by Forest-Gio** 2023-03-28 10:51 UTC
Labels: bug
